image: Visual Studio 2019
platform:
   - amd64

environment:
   APPVEYOR_API_TOKEN:
      secure: qTt+0485sfAXM2Sz+QLZ+jjziNf4One8/A062QFN1a4=
   GITHUB_API_TOKEN:
      secure: TpVl9vErdKkXR/RUlVtUDfeITAn5BtOhG3JxiFJRGp85c3B7boCFf6CDOxNgMr/m
   DEPLOY_BRANCH: 'master'
   
# branches:
#    only:
#       - master

skip_tags: true

build_script:
   - ps: |
      $ErrorActionPreference = "Stop"
      
      $env:RELEASE_NUMBER = 3
      $env:HASH = "dc68424"

      Update-AppveyorBuild -Version "1.${env:build}-${env:RELEASE_NUMBER}-${env:HASH}"

artifacts: off
   
deploy: off
